### ISSUE TITLE
V2.8.1 Release?

### ISSUE THREAD

**Issue by silvanshade** [XUANTIE-RV/xuantie-gnu-toolchain#13]
I notice that there is a `v2.8.1` toolchain release available for download:

https://occ-oss-prod.oss-cn-hangzhou.aliyuncs.com/resource/1705395627867/Xuantie-900-gcc-linux-5.10.4-glibc-x86_64-V2.8.1-20240115.tar.gz

But there seems to be no release for `v2.8.1` in this repository.

Can someone update the releases here so that it's possible to compile our own binaries from the release tag?

**Comment by Cooper-Qu** [comment]
Thank you for the reminder, the code for V2.8.1 has been pushed.
https://github.com/T-head-Semi/xuantie-gnu-toolchain/releases/tag/V2.8.1
