### ISSUE TITLE
Some issues I met while testing XTheadCondMov extension

### ISSUE THREAD

**Issue by dzhang28** [XUANTIE-RV/xuantie-gnu-toolchain#15]
I downloaded the latest v2.8.1 toolchain (Xuantie-900-gcc-linux-5.10.4-glibc-x86_64-V2.8.1-20240115.tar.gz).
I wrote a c file <mvnez.c> with content as follows:

```
#include <stdio.h>

#ifdef NO_INLINE
__attribute__((noinline))
#endif
int testCondMov(int condition, int value)
{
#ifdef USE_ASM
    asm volatile ("mvnez a0, a1, a0\n\t");
#else
    return condition != 0 ? value : 0;
#endif
}

int main()
{
    int cond, val, result;

    printf("Input the condition: ");
    scanf("%d", &cond);

    printf("Input the value: ");
    scanf("%d", &val);

    result = testCondMov(cond, val);
    printf("testCondMov(condition, value) = %d\n", result);

    return 0;
}
```

I tried seveal methods to see if correct conditional move code can be generated.

### Issue 1: Unexpected code was generated if the test function is declared without inline attribute.

I tried both _riscv64-unknown-linux-gnu-gcc -O2 mvnez.c_ and _riscv64-unknown-linux-gnu-gcc -O3 mvnez.c_ (same machine codes 
 were generated).
I can see mveqz instruction is generated in testCondMov():
![image](https://github.com/T-head-Semi/xuantie-gnu-toolchain/assets/26659178/46a008b7-f3f8-4270-969c-ba4a8d23e274)

But in the main() function, legacy instructions were used which would use 1 more instruction:
![image](https://github.com/T-head-Semi/xuantie-gnu-toolchain/assets/26659178/8119a9c1-215f-414e-9f75-532251ecd975)

### Issue 2: mvnez should be generated instead of mveqz
Actually this issue can be observed in the pictures shown under issue 1.
Anyway let me list it separately here.

This time I enable the 'NO_INLINE' attribute.
Again I tried both _riscv64-unknown-linux-gnu-gcc -O2 mvnez.c -DNO_INLINE_ and _riscv64-unknown-linux-gnu-gcc -O3 mvnez.c -DNO_INLINE_ (same machine codes were generated).

What I expect here is that 'mvnez a0, a1, a0' shall be generated instead of mveqz.
Obviously mvnez would save 1 instruction here.
![image](https://github.com/T-head-Semi/xuantie-gnu-toolchain/assets/26659178/bb7a19cf-6910-4291-9fef-cf52c1c6abae)

### Issue 3:  Inline asm code was not handled correctly if '-O3' enabled
This time I enable 'USE_ASM'.
Again I tried both _riscv64-unknown-linux-gnu-gcc -O2 mvnez.c -DNO_INLINE -DUSE_ASM_ and _riscv64-unknown-linux-gnu-gcc -O3 mvnez.c -DNO_INLINE -DUSE_ASM_.

Machine code was generated properly in '-O2' case.
But in '-O3' case, wrong machine code was generated!!!
It would cause the test program cannot function normally in runtime!!!

There are 2 main differences.
Firstly a new subroutine 'testCondMov.constprop.0' was generated:
![image](https://github.com/T-head-Semi/xuantie-gnu-toolchain/assets/26659178/2a1f86b6-c424-4e0c-b678-9c4184f63f2a)

Secondly there are 2 insturctions missed in main() just before calling 'testCondMov.constprop.0':
![image](https://github.com/T-head-Semi/xuantie-gnu-toolchain/assets/26659178/6a664fcc-87db-4eed-aef1-3809c35ca045)

So wrong values would be passed to the testCondMov().

BTW, even though correct code was generated in '-O2' case, wouldn't it be better if instruction 'lwd a0,a1,(sp),1,3' was generated instead of 'lw  a1,12(sp) / lw  a0,8(sp)'???

**Comment by Cooper-Qu** [comment]
Sorry for the delay in replying. I try my best to respond promptly, but sometimes it's difficult to do so.

### Issue1

It is a bug and has been fixed. https://github.com/T-head-Semi/gcc/commit/0cd3b72d15997d357219074902b106b24b6a5202

### Issue2

Yes, it can be optimized. https://github.com/T-head-Semi/gcc/commit/441be8d9fb14df7cd2cb862592aa1b567f03ed26

### Issue3

You should use the 'asm' correctly. Add inputs and outputs to asm expressions like the code below, otherwise the compiler may consider the parameters as useless and optimize them away.
`
int testCondMov(int condition, int value)
{
    asm volatile ("mvnez %0, %1, %0": "+r"(condition): "r"(value));
    return condition;
}
`

**Comment by Cooper-Qu** [comment]
The issue has been resolved, and I'm closing it for now. Feel free to contact me if you have any further questions.
