### ISSUE TITLE
v2.10.1 release

### ISSUE THREAD

**Issue by kailiu42** [XUANTIE-RV/xuantie-gnu-toolchain#19]
Hi, as v2.10.1 toolchain binary has been released: https://www.xrvm.cn/community/download?id=4333581795569242112

Could you also release the code here?

**Comment by kailiu42** [comment]
Well it's 2.10.2 now.

**Comment by OctopusET** [comment]
+1

**Comment by OctopusET** [comment]
v3.0.1 is released
https://www.xrvm.cn/community/download?id=4382928864901402624

**Comment by Cooper-Qu** [comment]
I'm sorry for the long wait. The code for version 2.10.2 has been uploaded. The code for version 3.0.1 will be uploaded after the disclosure process is completed.

https://github.com/XUANTIE-RV/xuantie-gnu-toolchain/commit/dcf93b23d3eed54a4fcfe9c07c6d3e2969642433

**Comment by kailiu42** [comment]
Thanks. Would you mind tag the repo?

**Comment by Cooper-Qu** [comment]
> Thanks. Would you mind tag the repo?

Done!
