### ISSUE TITLE
GDB segfaults

### ISSUE THREAD

**Issue by dengeltheyounger** [XUANTIE-RV/xuantie-gnu-toolchain#2]
When building the toolchain, I've noticed that everything works as expected, except that GDB segfaults on start up. When I run Valgrind, I get an "invalid read of size 8".

**Comment by Cooper-Qu** [comment]
Sorry for not replying in time, our code has been updated to the latest version 3 months ago, does this problem still exist?

**Comment by Cooper-Qu** [comment]
Close this issue because there is no response, if this problem still exists, please reopen
