### ISSUE TITLE
When executing the make command, an error is reported

### ISSUE THREAD

**Issue by JLIANG0717** [XUANTIE-RV/xuantie-gnu-toolchain#3]
/bin/bash ../.././riscv-gcc/gcc/../move-if-change tmp-automata.c insn-automata.c
automatav=$(echo $(csplit insn-automata.c /parallel\ compilation/ -k -s {15} -f insn-automata -b "%d.c" 2>&1));\
[ ! "$automatav" ] || grep "match not found" <<< $automatav
make[2]: *** [Makefile:2411：s-automata] 错误 1
make[2]: 离开目录“/home/li/t-head-semi/xuantie-gnu-toolchain/build-gcc-linux-stage1/gcc”
make[1]: *** [Makefile:4372：all-gcc] 错误 2
make[1]: 离开目录“/home/li/t-head-semi/xuantie-gnu-toolchain/build-gcc-linux-stage1”

**Comment by wujw20** [comment]
I also encountered this problem, can you tell me how you solved it?

**Comment by JLIANG0717** [comment]
The solution is in the readme file: "riscv-gnu-toolchain contain stable but not latest source for each submodule"
![Screenshot_2023_0329_014848](https://user-images.githubusercontent.com/88592483/228324966-e15da573-a17e-4b6e-8d9f-e71a9650f467.png)

**Comment by YI-MAX-YAN** [comment]
git submodule update --remote
fatal: Needed a single revision
Unable to find current origin/master revision in submodule path 'riscv-glibc'
