### ISSUE TITLE
Internal compiler error with RVV 0.7

### ISSUE THREAD

**Issue by mshabunin** [XUANTIE-RV/xuantie-gnu-toolchain#5]
I'm observing compiler error when building some code with RVV 0.7 support enabled. I've built toolchain  2.6.1 using this repository commit [23fdf1028b63bb52ec0900f0021617e50c1f9af0](https://github.com/T-head-Semi/xuantie-gnu-toolchain/commit/23fdf1028b63bb52ec0900f0021617e50c1f9af0).

### Steps to reproduce:
1. Get repository and build toolchain:
  ```
  git clone \
        --depth=1 \
        https://github.com/T-head-Semi/xuantie-gnu-toolchain
  cd xuantie-gnu-toolchain
  git submodule init || true
  git submodule update \
        --recursive \
        --recommend-shallow \
        --progress
  ./configure --prefix=/opt/riscv --with-arch=rv64gc --with-abi=lp64d
  make -j12 linux
  ```
2. Build test application (attached) using this toolchain:
  ```
/opt/riscv/bin/riscv64-unknown-linux-gnu-g++ \
    -march=rv64gcv0p7 \
    -mabi=lp64d \
    -g \
    -O2 \
    rvv_ice_071.cpp \
    -o build/rvv_ice_071
  ```

### Output:
```
rvv_ice_071.cpp: In function 'int test(int*, int)':
rvv_ice_071.cpp:52:1: error: could not split insn
   52 | }
      | ^
(insn 275 442 177 (set (reg:VNx2DI 98 v2 [orig:143 _35 ] [143])
        (unspec:VNx2DI [
                (reg:VNx2DI 97 v1 [orig:140 _31 ] [140])
            ] UNSPEC_VWLDST)) "/opt/riscv/lib/gcc/riscv64-unknown-linux-gnu/10.2.0/include/riscv_vector.h":3686:1 60819 {movvnx2di_v0p7}
     (nil))
during RTL pass: final
rvv_ice_071.cpp:52:1: internal compiler error: in final_scan_insn_1, at final.c:3073
0x7f9f67029d8f __libc_start_call_main
	../sysdeps/x86/libc-start.c:58
0x7f9f67029e3f __libc_start_main_impl
	../sysdeps/nptl/libc_start_call_main.h:392
Please submit a full bug report,

with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
```
### Notes/questions:
* Source code: [rvv_ice_071.txt](https://github.com/T-head-Semi/xuantie-gnu-toolchain/files/10758707/rvv_ice_071.txt) - this reproducer is as minimal as I could make, most of modifications causes problem to disappear
* Pre-built toolchain 2.6.1 works without issues (Xuantie-900-gcc-linux-5.10.4-glibc-x86_64-V2.6.1-20220906.tar.gz here: https://occ.t-head.cn/community/download?id=4090445921563774976). What is the difference between that toolchain and this one? Is there anything I should do to build that version from sources?
* Only reproduced with `-O2` or `-O3`
* Only reproduced with `v0p7`, arch `rv64gcv` works fine

**Comment by Cooper-Qu** [comment]
Hi, the bug is caused by a missing patch, and it has been cherry-pick now in gcc.
  https://github.com/T-head-Semi/gcc/commit/2346dc0cdb4e9a24b1bd6ccf982073582fd9ace4
And also update the commit in this repo. Thank you for submitting the bug.

**Comment by Cooper-Qu** [comment]
@mshabunin Found a bug on O0, and the patch has been updated, 
https://github.com/T-head-Semi/gcc/commit/8a5a8d17caf929ca7c2caba66ddb17de8778b511
if you download the previous version, please update it.

**Comment by mshabunin** [comment]
@Cooper-Qu , thank you. I've verified that my workload (OpenCV library) can be built without issues with both `-O0` and `-O3` with the latest toolchain revision and `v0p7` support.
