### ISSUE TITLE
small improvements in README.md

### ISSUE THREAD

**Issue by Popolon** [XUANTIE-RV/xuantie-gnu-toolchain#6]
First, thank you very much for your great work on both hardware and software.

The Arch Linux package installation can be improved a bit by adding the <code>--needed</code> option, to avoid to reinstall already installed package. It will still upgrade pacakges when new versions are available:
<pre>$ sudo pacman -Syyu --needed autoconf automake curl python3 mpc mpfr gmp gawk base-devel bison flex texinfo gperf libtool patchutils bc zlib expat</pre>

There is also mentioned in the <code>README.md</code> that manuealy recursive fetch of submodules is not needed, but it fails without recursive fetch for me (on both x86_64 and riscv64/qemu Arch Linux system) with the following error:

<pre>
[root@archriscv xuantie-gnu-toolchain]# ./configure --prefix=/opt/riscv
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for fgrep... /usr/bin/grep -F
checking for grep that handles long lines and -e... (cached) /usr/bin/grep
checking for bash... /bin/sh
checking for __gmpz_init in -lgmp... yes
checking for mpfr_init in -lmpfr... yes
checking for mpc_init2 in -lmpc... yes
checking for curl... /usr/bin/curl
checking for wget... /usr/bin/wget
checking for ftp... /usr/bin/ftp
configure: creating ./config.status
config.status: creating Makefile
config.status: creating scripts/wrapper/awk/awk
config.status: creating scripts/wrapper/sed/sed
[root@archriscv xuantie-gnu-toolchain]# make -j64
cd /opt/arc/t-head/xuantie-gnu-toolchain
cd /opt/arc/t-head/xuantie-gnu-toolchain
cd /opt/arc/t-head/xuantie-gnu-toolchain
cd /opt/arc/t-head/xuantie-gnu-toolchain
rm -rf stamps/build-binutils-newlib build-binutils-newlib
rm -rf stamps/build-gdb-newlib build-gdb-newlib
mkdir build-binutils-newlib
mkdir build-gdb-newlib
cd build-binutils-newlib && CC_FOR_TARGET=riscv64-unknown-elf-gcc /opt/arc/t-head/xuantie-gnu-toolchain/riscv-binutils/configure \
	--target=riscv64-unknown-elf \
	 \
	--prefix=/opt/riscv \
	 \
	--disable-werror \
	--with-expat=yes  \
	--disable-gdb \
	--disable-sim \
	--disable-libdecnumber \
	--disable-readline
cd build-gdb-newlib && CC_FOR_TARGET=riscv64-unknown-elf-gcc /opt/arc/t-head/xuantie-gnu-toolchain/riscv-gdb/configure \
	--target=riscv64-unknown-elf \
	 \
	 \
	 \
	--prefix=/opt/riscv \
	 \
	--disable-werror \
	--with-expat=yes --with-python=no  \
	--enable-gdb \
	--disable-gas \
	--disable-binutils \
	--disable-ld \
	--disable-gold \
	--disable-gprof
/bin/sh: line 1: /opt/arc/t-head/xuantie-gnu-toolchain/riscv-binutils/configure: No such file or directory
make: *** [Makefile:509: stamps/build-binutils-newlib] Error 127
make: *** Waiting for unfinished jobs....
/bin/sh: line 1: /opt/arc/t-head/xuantie-gnu-toolchain/riscv-gdb/configure: No such file or directory
make: *** [Makefile:528: stamps/build-gdb-newlib] Error 127
</pre>

I just followed the installation instructions made in this ticket and it worked fine:  
https://github.com/T-head-Semi/xuantie-gnu-toolchain/issues/5#issue-1588095595

In case of, there is an error at the beginning of the process, but it isn't blocking to build the whole toolchain:
<pre>fatal: No url found for submodule path 'riscv-libcc-runtime' in .gitmodules</pre>

I was able to build booting kernel for D1, with it :).

**Comment by Popolon** [comment]
<code>riscv64-linux-gnu-g++</code> given in the pointed out ticket is missing, only <code>riscv64-linux-gnu-c++filt</code> is here, but looking at other cross-compilation toolchain, it seems to be the same.

**Comment by Cooper-Qu** [comment]
@Popolon 
The --needed option has been added, thanks for the suggestion.
https://github.com/T-head-Semi/xuantie-gnu-toolchain/commit/734ac9bb3a92f142bd9d9f59b348716b281773c2

And the error:
> fatal: No url found for submodule path 'riscv-libcc-runtime' in .gitmodules

It's because we didn't clean up the submodules. This does cause some confusion, thanks for pointing it out.
https://github.com/T-head-Semi/xuantie-gnu-toolchain/commit/42de3e30978e3606cd5a9367bc0702a4b2163075

> riscv64-linux-gnu-g++ given in the pointed out ticket is missing, only riscv64-linux-gnu-c++filt is here, but looking at other cross-compilation toolchain, it seems to be the same.

The riscv64-linux-gnu-g++ and riscv64-linux-gnu-c++filt are two different tools. riscv64-linux-gnu-c++filt comes from binutils and was generated at an earlier stage,  and riscv64-linux-gnu-g++ is generated in the final stage. So to confirm whether the project has been successfully builded.

**Comment by Popolon** [comment]
@Cooper-Qu Thanks for your feedback, and sorry to the late answer. 
The C++ binary is build now, but there is still the need to follow #5 build options.
